csharp/Assessment/Assessment/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assessment.Controllers
{
    public class MainController : Controller
    {
        //
        // GET: /Main/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string AuthenType, string username, string passsword)
        {
            if (AuthenType.Equals("teacher")) // คุณครู
            {
                Session["AuthenType"] = AuthenType;
                return Redirect("Assessment/Create");
            }
            else if (AuthenType.Equals("officer")) // เจ้าหน้าที่
            {
                Session["AuthenType"] = AuthenType;
                return Redirect("School/Index");
            }

            return View();
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(string account)
        {
            return View("Login");
        }
    }
}

csharp/Assessment/Assessment/Controllers/ReportController.cs
using Assessment.Class;
using Assessment.Models;
using Newtonsoft.Json;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assessment.Controllers
{
    public class ReportController : Controller
    {
        public ActionResult Index()
        {
            //var cm = new Common();
            //var sch = cm.GetSchool();
            //var schG = cm.GetSchoolGroup();
            //var S = cm.GetStudent();
            //var sD = cm.GetStudentDetail();
            //var schT = cm.GetSchoolType();
            //////var dT = GetDisabledType();
            //var amt = cm.GetAssessment();
            //var query = from _sch in sch
            //            from _schG in schG
            //            from _schT in schT
            //            from _S in S
            //            from _sD in sD
            //            from _amt in amt
            //            where _schG.scgroup_id == _sch.scgroup_id && _schT.sctype_id == _sch.sctype_id && _S.sc_id == _S.sc_id && _sD.std_id == _S.std_id && _amt.std_id == _S.std_id && _sch.sc_name == "บ้านโคกกระเพอ"
            //            select new  { _sch.sc_name, _schG.scgroup_name, _S.std_title, _S.std_firstname, _S.std_lastname, _S.std_idcard, _S.std_birthday, _S.std_grade, _sD.dsbtype_id, _schT.sctype_name, _amt.ass_certdisable };
            //var lst = new List<BySchoolModel>();


            //foreach (var obj in query)
            //{
            //    var model = new BySchoolModel();
            //    model.sc_name = obj.sc_name;
            //}
            //var result = JsonConvert.DeserializeObject<List<SchoolModel>>(query);
            //ViewData["GetDataSchool"] = result;
            return View();
        }

        public ActionResult TestExportToExcel(String type)
        {
            string path = HttpContext.Server.MapPath("~/App_Data/DataStudent.txt");
            string data = System.IO.File.ReadAllText(path);
            String namefile = "";
            List<StudentModel> List = JsonConvert.DeserializeObject<List<StudentModel>>(data);

            if (List.Count > 0)
            {
                try
                {
                    System.IO.MemoryStream streamExcel = new System.IO.MemoryStream();
                    var cm = new Common();
                    using (var excel = new ExcelPackage(streamExcel))
                    {
                        System.IO.MemoryStream memStream = new System.IO.MemoryStream();
                        int[] sum = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };

                        var Worksheets = excel.Workbook.Worksheets.Add("Sheet1");
                        int rows = 1;
                        int column = 1;
                        if (type == "รายงานรายโรงเรียน")
                        {
                            #region "รายงานรายโรงเรียน"
                            namefile = "รายงานรายโรงเรียน";
                            GenHeadTableTabBySchool(ref Worksheets, ref rows);
                            var sch = cm.GetSchool();
                            var schG = cm.GetSchoolGroup();
                            var S = cm.GetStudent();
                            var sD = cm.GetStudentDetail();
                            var schT = cm.GetSchoolType();
                            ////var dT = GetDisabledType();
                            var amt = cm.GetAssessment();
                            var query = from _sch in sch
                                        from _schG in schG
                                        from _schT in schT
                                        from _S in S
                                        from _sD in sD
                                        from _amt in amt
                                        where _schG.scgroup_id == _sch.scgroup_id && _schT.sctype_id == _sch.sctype_id && _S.sc_id == _S.sc_id && _sD.std_id == _S.std_id && _amt.std_id == _S.std_id && _sch.sc_name == "บ้านโคกกระเพอ"
                                        select new { _sch.sc_name, _schG.scgroup_name, _S.std_title, _S.std_firstname, _S.std_lastname, _S.std_idcard, _S.std_birthday, _S.std_grade, _sD.dsbtype_id, _schT.sctype_name, _amt.ass_certdisable };
                            rows += 2;
                            int[] sumSub = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
                            foreach (var aa in query.OrderBy(x => x.scgroup_name))
                            {
                                BorderCells(ref Worksheets, rows, column);
                                Worksheets.Cells[rows, column++].Value = (rows - 4).ToString();
                                BorderCells(ref Worksheets, rows, column);
                                Worksheets.Cells[rows, column++].Value = aa.sc_name;
                                BorderCells(ref Worksheets, rows, column);
                                Worksheets.Cells[rows, column++].Value = aa.scgroup_name;
                                BorderCells(ref Worksheets, rows, column);
                                Worksheets.Cells[rows, column++].Value = aa.std_title + aa.std_firstname + " " + aa.std_lastname;
                                BorderCells(ref Worksheets, rows, column);
                                Worksheets.Cells[rows, column++].Value = aa.std_idcard;
                                BorderCells(ref Worksheets, rows, column);
                                Worksheets.Cells[rows, column++].Value = (2558 - Convert.ToInt16(aa.std_birthday.Split('-')[0]));
                                BorderCells(ref Worksheets, rows, column);
                                Worksheets.Cells[rows, column++].Value = aa.std_grade;
                                BorderCells(ref Worksheets, rows, column);
                                Worksheets.Cells[rows, column + aa.dsbtype_id - 1].Value = "/";
                                Worksheets.Cells[rows, column + aa.dsbtype_id - 1].Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
                                BorderCells(ref Worksheets, rows, column);

                                int i = Convert.ToInt16(aa.dsbtype_id);
                                sumSub[i - 1]++;
                                column += 9;
                                BorderCells(ref Worksheets, rows, column);
                                Worksheets.Cells[rows, column++].Value = aa.sctype_name;
                                BorderCells(ref Worksheets, rows, column);
                                Worksheets.Cells[rows, column++].Value = aa.ass_certdisable;
                                rows++; //dsbtype_id
                                column = 1;
                            }
                            rows++;
                            column = 8;

                            WriteExcele(ref Worksheets, "B", rows, "G", rows, "รวม");
                            int flagRow = rows - 2;
                            BorderCells(ref Worksheets, rows, column);
                            Worksheets.Cells[rows, column].Value = sumSub[column - 8];
                            column++;
                            BorderCells(ref Worksheets, rows, column);
                            Worksheets.Cells[rows, column].Value = sumSub[column - 8];
                            column++;
                            BorderCells(ref Worksheets, rows, column);
                            Worksheets.Cells[rows, column].Value = sumSub[column - 8];
                            column++;
                            BorderCells(ref Worksheets, rows, column);
                            Worksheets.Cells[rows, column].Value = sumSub[column - 8];
                            column++;
                            BorderCells(ref Worksheets, rows, column);
                            Worksheets.Cells[rows, column].Value = sumSub[column - 8];
                            column++;
                            BorderCells(ref Worksheets, rows, column);
                            Worksheets.Cells[rows, column].Value = sumSub[column - 8];
                            column++;
                            BorderCells(ref Worksheets, rows, column);
                            Worksheets.Cells[rows, column].Value = sumSub[column - 8];
                            column++;
                            BorderCells(ref Worksheets, rows, column);
                            Worksheets.Cells[rows, column].Value = sumSub[column - 8];
                            column++;
                            BorderCells(ref Worksheets, rows, column);
                            Worksheets.Cells[rows, column].Value = sumSub[column - 8];

                            rows += 3;
                            WriteExcele(ref Worksheets, "A", rows, "R", rows, "ประเภทความพิการ 1=ด้านการมองเห็น 2=ด้านการได้ยิน 3=ด้านสติปัญญา 4=ด้านร่างกาย/สุขภาพ 5=ด้านการเรียนรู้");
                            rows++;
                            WriteExcele(ref Worksheets, "A", rows, "R", rows, "6=ด้านการพูด/ภาษา 7=ด้านพฤติกรรมอารมร์ 8=ออทิสติค 9=พิการซ้อน");

                            for (int i = 5; i <= flagRow; i++)
                            {
                                for (int j = 8; j <= 16; j++)
                                {
                                    BorderCells(ref Worksheets, i, j);
                                }
                            }
                            for (int j = 1; j <= 18; j++)
                            {
                                BorderCells(ref Worksheets, rows - 5, j);
                            }
                            BorderCells(ref Worksheets, rows - 4, 1);
                            BorderCells(ref Worksheets, rows - 4, 17);
                            BorderCells(ref Worksheets, rows - 4, 18);
                            #endregion
                        }
                        else if (type == "")
                        {

csharp/Assessment/Assessment/Controllers/SchoolController.cs
using Assessment.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assessment.Controllers
{
    public class SchoolController : Controller
    {
        //
        // GET: /School/

        public ActionResult Index()
        {
            string path = HttpContext.Server.MapPath("~/App_Data/DataSchool.txt");
            string data = System.IO.File.ReadAllText(path);
            var result = JsonConvert.DeserializeObject<List<SchoolModel>>(data);
            ViewData["GetDataSchool"] = result;
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Edit(string id)
        {
            return View();
        }

        public ActionResult Type()
        {
            string path = HttpContext.Server.MapPath("~/App_Data/DataSchoolType.txt");
            string data = System.IO.File.ReadAllText(path);
            var result = JsonConvert.DeserializeObject<List<SchoolTypeModel>>(data);
            ViewData["DataSchoolType"] = result;
            return View();
        }

        public ActionResult TypeCreate()
        {
            return View();
        }

        public ActionResult TypeEdit(string id)
        {
            return View();
        }

        public ActionResult Group()
        {
            string path = HttpContext.Server.MapPath("~/App_Data/DataSchoolGroup.txt");
            string data = System.IO.File.ReadAllText(path);
            var result = JsonConvert.DeserializeObject<List<SchoolGroupModel>>(data);
            ViewData["DataSchoolGroup"] = result;
            return View();
        }

        public ActionResult GroupCreate()
        {
            return View();
        }

        public ActionResult GroupEdit(string id)
        {
            return View();
        }
    }
}

csharp/Assessment/Assessment/Controllers/SettingController.cs
using Assessment.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assessment.Controllers
{
    public class SettingController : Controller
    {
        //
        // GET: /Setting/

        public ActionResult SystemConfig()
        {
            string path = HttpContext.Server.MapPath("~/App_Data/DataSystemConfig.txt");
            string data = System.IO.File.ReadAllText(path);
            var result = JsonConvert.DeserializeObject<List<SystemConfigModel>>(data);
            ViewData["DataSystemConfig"] = result;
            return View();
        }

        public ActionResult SystemConfigCreate()
        {
            return View();
        }

        public ActionResult SystemConfigEdit(string id)
        {
            return View();
        }
        
    }
}

csharp/Assessment/Assessment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/css")
    @RenderSection("MyStyle", required: false)
</head>
<body>
    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index","Main")">
                    <img src="~/Content/img/Logo.png" />
                </a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="icon-user"></i>&nbsp; JOHZA <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="/"><i class="icon-power"></i>&nbsp; Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
@*                        <li>
                            <a href="@Url.Action("Index","Main")"><i class="icon-grid"></i>&nbsp; หน้าหลัก</a>
                        </li>*@
                        @if (Session["AuthenType"].ToString().Equals("teacher"))
                        {
                        <li>
                            <a href="#"><i class="icon-users"></i>&nbsp; จัดการข้อมูลคุณครู<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">

                                <li>
                                    <a href="@Url.Action("Index", "Teacher")">รายชื่อคุณครู</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Create", "Teacher")">เพิ่มข้อมูลคุณครู</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="icon-graduation"></i>&nbsp;  จัดการข้อมูลนักเรียน<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="@Url.Action("Index", "Student")">รายชื่อนักเรียน</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Create", "Student")">เพิ่มข้อมูลนักเรียน</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li> 
                        } 
                        @if (Session["AuthenType"].ToString().Equals("officer"))
                        {
                        <li>
                            <a href="#"><i class="icon-star"></i>&nbsp;  จัดการข้อมูลโรงเรียน<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="@Url.Action("Index", "School")">รายชื่อโรงเรียน</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Type", "School")">ประเภทโรงเรียน</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Group", "School")">รายชื่อเครือข่าย</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        }
                        @if (Session["AuthenType"].ToString().Equals("teacher"))
                        {
                        <li>
                            <a href="#"><i class="icon-note"></i>&nbsp;  ข้อมูลประเมิน<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="@Url.Action("Index", "Assessment")">รายการใบประเมิน</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Create", "Assessment")">เพิ่มข้อมูลใบประเมิน</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        }

                        <li>
                            <a href="#"><i class="icon-bar-chart"></i>&nbsp;  รายงาน<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                @if (Session["AuthenType"].ToString().Equals("teacher"))
                                {
                                    <li>
                                        <a href="@Url.Action("School", "Report")">รายงานรายโรงเรียน</a>
                                    </li>
                                }
                                @if (Session["AuthenType"].ToString().Equals("officer"))
                                {
                                    <li>
                                        <a href="@Url.Action("AllSchool", "Report")">โรงเรียนทั้งหมด </a>
                                    </li>                         
                                    <li>
                                        <a href="@Url.Action("Zone", "Report")">โรงเรียนที่คัดกรอง </a>
                                    </li>            
                                    <li>
                                        <a href="@Url.Action("Level", "Report")">ข้อมูลระดับชั้น</a>
                                    </li> 
                                }
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        
                        @if (Session["AuthenType"].ToString().Equals("officer"))
                        {
                        <li>
                            <a href="#"><i class="icon-settings"></i>&nbsp;  ตั้งค่า<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="@Url.Action("SystemConfig", "Setting")">เวลาเปิด-ปิดระบบ</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        }
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        @RenderBody()
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->
    @Scripts.Render("~/scripts")
    @RenderSection("scripts", required: false)
    @RenderSection("MyScripts", required: false)

    
</body>
</html>