csharp/Assessment/Assessment/Controllers/AssessmentController.cs
using Assessment.Class;
using Assessment.Models;
using Newtonsoft.Json;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assessment.Controllers
{
    public class AssessmentController : Controller
    {
        //
        // GET: /Assessment/

        public ActionResult Index()
        {
            string path = HttpContext.Server.MapPath("~/App_Data/DataAssessment.txt");
            string data = System.IO.File.ReadAllText(path);
            var result = JsonConvert.DeserializeObject<List<AssessmentModel>>(data);
            ViewData["GetDataAssessment"] = result;
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult PrintAssemssment()
        {
            try
            {
                var cm = new Common();
                var A = cm.GetAssessment();
                var Ad = cm.GetAssessDetail();
                var At = cm.GetAssessType();
                var S = cm.GetStudent();

                var query = from _A in A
                            from _Ad in Ad
                            from _At in At
                            where _A.ass_id == _Ad.ass_id && _A.ass_type_id == _At.asstype_id.ToString() && _Ad.ass_no == _At.ass_no
                            select new { _At.question, _Ad.answer };
                DataTable dt = new DataTable();
                DataRow dr;
                dt.Columns.Add("question");
                dt.Columns.Add("answer");
                foreach (var aa in query)
                {
                    dr = dt.NewRow();
                    dr["question"] = aa.question;
                    dr["answer"] = aa.answer;
                    dt.Rows.Add(dr);
                }
                if (dt.Rows.Count > 0)
                {
                    using (CrystalDecisions.CrystalReports.Engine.ReportClass rptH = new CrystalDecisions.CrystalReports.Engine.ReportClass())
                    {
                        string path = HttpContext.Server.MapPath("~/App_Data/reportPdf.rpt");
                        rptH.FileName = path;
                        rptH.Load();
                        rptH.SetDataSource(dt);
                        //   rptH.SetParameterValue("isAdmin", (user.Role.RoleName == RoleName.Admintstrator ? "T" : "F"));
                        System.IO.Stream stream = rptH.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
                        rptH.Close();
                        return File(stream, "application/pdf");
                    }
                }
                return new EmptyResult();

            }
            catch (Exception ex)
            {

                return new EmptyResult();
            }
        }

 
    }

}

csharp/Assessment/Assessment/Views/Assessment/Index.cshtml
@using Assessment.Models;
@{
    ViewBag.Title = "ข้อมูลประเมิน";
}
<br />
<ol class="breadcrumb">
    <li><i class="icon-grid">&nbsp; </i><a href="/">หน้าหลัก</a></li>
    <li><a href="#">ข้อมูลประเมิน</a></li>
    <li class="active">รายการใบประเมิน</li>
</ol>

<div class="panel panel-default">
    <div class="panel-heading">
        <i class="icon-notebook"></i>&nbsp; รายการใบประเมิน
        <a href="@Url.Action("Create")" class="btn btn-success btn-xs pull-right"><i class="icon-plus"></i>&nbsp; เพิ่มข้อมูลใบประเมิน</a>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="dataTable_wrapper">
            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                    <tr>
                        <th style="width:120px">รหัสใบประเมิน</th>
                        <th>นักเรียนที่ประเมิน</th>
                        <th>คุณครูผู้ประเมิน</th>
                        <th>ประเภทแบบประเมิน</th>
                        <th>คะแนนที่ได้</th>
                        <th>ผลการประเมิน</th>
                        <th class="text-center" style="width:100px;"></th>
                    </tr>
                </thead>
                <tbody>
                    @{                       
                        if ((IEnumerable<AssessmentModel>)ViewData["GetDataAssessment"] != null)
                        {
                            foreach (var item in (IEnumerable<AssessmentModel>)ViewData["GetDataAssessment"])
                            {
                            <tr>
                                <td>@item.ass_id</td>
                                <td>@item.std_id</td>
                                <td>@item.tc_id</td>
                                <td>บกพร่องทางการมองเห็น</td>
                                <td>@item.ass_score</td>
                                <td>@item.ass_result</td>
                                <td class="text-center">
                                    <a href="#"><img src="~/Content/img/toolbar_delete_24.png" style="width:20px;" class="btnDelete" /></a>
                                    <a href="#"><img src="~/Content/img/toolbar_edit_green_24.png" style="width:20px;"  /></a>
                                    <a href="@Url.Action("PrintAssemssment", "Assessment")"><img src="~/Content/img/toolbar_print_24.png" style="width:20px;" /></a>
                                </td>
                            </tr>
                            }
                        }
                    }
                </tbody>
            </table>
            <nav>
              <ul class="pagination">
                <li>
                  <a href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                  </a>
                </li>
                <li><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li>
                  <a href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                  </a>
                </li>
              </ul>
            </nav>
        </div>
    </div>
    <!-- /.panel-body -->
     
</div>
<!-- /.panel -->
@section MyScripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $("a > img.btnDelete").click(function () {
                if (confirm("ยืนยันการลบข้อมูล ?")) {
                }
                return false;
            });
        });
    </script>
}